#!/usr/bin/env bash
set -eu

MODEL="${GLOLLAMA_MODEL:-llama3}"
CUSTOM_MODEL="${MODEL}-custom"

# save history
HIST_DIR="$HOME/.local/share/glollama/history"
mkdir -p "$HIST_DIR"

# create a custom model that focuses on brevity, if it doesn't already exist.
! ollama ls | grep -q "$CUSTOM_MODEL" && ollama create "$CUSTOM_MODEL"

# create this interaction's hist file
HIST_FILE="$HIST_DIR/$(date +%s).md"
echo "Saving interaction to $HIST_FILE"
echo "# $*" > "$HIST_FILE"

# invoke llm
ollama run "$CUSTOM_MODEL" "$@" | tee -a "$HIST_FILE"

# make it pop
glow --pager "$HIST_FILE"
